### ISSUE TITLE
Evaluate scraping frameworks and decide whether we need our own

### ISSUE THREAD

**Issue by blahah** [ContentMine/journal-scrapers#2]
Key to the mission is building a content mining system that can be sustained by a community of volunteers. To maximise sustainability we should choose or design the scraping system so that the barrier to becoming a contributor is a low as practically possible.

Existing scrapers fall into the following categories:
- Use a structured scraping framework but with each definition implemented in arbitrary code confirming to a basic protocol. Example: [Zotero translators](https://github.com/zotero/translators).
- Use a Domain Specific Language to create definitions. Example: [scrapi](https://github.com/assaf/scrapi).
- Learn the definition from user provided examples of paired documents and extracted datasets. Example: [scrapely](https://github.com/scrapy/scrapely).
- Use declarative, structured definitions in a data format like JSON. Example: [libKrake](https://github.com/KrakeIO/libkrake).

**Comment by kanzure** [comment]
Zotero translators can be repurposed. The way that I did this for paperbot ( https://github.com/kanzure/paperbot ) was through a local "headless" zotero server, which provides a simple API for executing the translators (scrapers). The advantage of this technique is that zotero's 100s of scrapers are constantly maintained by a great number of people.

**Comment by Blahah** [comment]
Indeed, and I considered this, but unfortunately the Zotero scrapers don't cover all the information we need. We would have to edit all the scrapers in the collection. What we've ended up with is a declarative framework that is much more powerful than the Zotero translators. Because it's declarative, we can build tools on top of it, for example tools that allow non-programmers to easily build scrapers (we have this currently in development).

Also worth noting is that our tool [getpapers](https://github.com/contentmine/getpapers), which uses various APIs to source papers and their associated (meta)data, can handle many things. Support for the crossref API is in the todo queue. With that, getpapers will be able to get most papers.

btw paperbot is very nice!

**Comment by kanzure** [comment]
I think that the zotero team can be convinced to switch to a different format if you can show that the alternative scrapers are just as comprehensive (if not more).

Yeah there's a large corpus of data from multiple years of active paperbot use, dunno if that would be useful to you. Mostly the available data is in the format of "requested paper url" (some abstract url) followed by paperbot either succeeding and returning a pdf, or failing and returning the html of a page that it couldn't parse at the time. Might be useful for unit testing datafodder, or for future studies perhaps interesting to see evolution of terrifying html and javascript on publisher sites.

**Comment by Blahah** [comment]
Good to know about Zotero - once our collection is at their level, we will explore that.

Is the paperbot corpus all open access stuff?

Looking at changes in publisher websites over time could be very interesting.

**Comment by kanzure** [comment]
Mixed access, some open-access.
